### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:msledl

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#115]
## Discipline Node Information

ATM

[msledl_v1.0_NSSDCA_20210428.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/6394106/msledl_v1.0_NSSDCA_20210428.tar.gz)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:msledl_v1.0_20210428

**Comment by c-suh** [comment]
set is in Pre-Ingest

**Comment by smclaughlin7** [comment]
@Astro-Joni @c-suh @jordanpadams  For this SIP

> urn:nasa:pds:system_bundle:product_sip_deep_archive:msledl_v1.0_20210428

our ingest process threw errors on four collection products because the inventory files have ".txt" for the extension instead of the expected ".csv" (or the less-preferred ".tab"). The Standards and DPH do not explicitly prohibit ".txt" or ".tab" for inventory files but all the examples and text use ".csv". Additionally inventory files are CSV-formatted so the extension should reflect that.

**Request:**  Could Atmospheres please:
1. change the extension of the four collection inventory files -- highlighted in green in [Issue115_CollCheckProcess_Step.xlsx](https://github.com/NASA-PDS/pdsen-operations/files/6516721/Issue115_CollCheckProcess_Step.xlsx) -- from ".txt" to ".csv".
3. update the file names in the associated collection product labels
4. run the Deep Archive software to make a new SIP and submit it

**Note to EN:** We had an identical problem last month with submission #60 from Geosciences.

Thanks!

**Comment by jordanpadams** [comment]
@smclaughlin7 I think this is a constraint we should discuss offline. I do not believe we should impose file naming constraints beyond what the PDS4 Standards impose.

**Comment by smclaughlin7** [comment]
@jordanpadams We/NSSDCA will revise our ingest software to remove the constraint on file extensions for collection inventory files.  In the interim, we will manually remove those flagged errors and proceed with ingesting SIP

> urn:nasa:pds:system_bundle:product_sip_deep_archive:msledl_v1.0_20210428

No action needed from Joni or Catherine.

**Comment by jordanpadams** [comment]
thanks @smclaughlin7 !

**Comment by c-suh** [comment]
@Astro-Joni, this set has been successfully archived!
