### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:compil-comet::1.0

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS/pdsen-operations#117]
## Discipline Node Information

**Delivering Node**: SBN/UMD

**NSSDCA Delivery Package**: https://pdssbn.astro.umd.edu/holdings/pds4-compil-comet-v1.0/SUPPORT/NSSDCA/

This is my first test of uploading a bundle that has been superseded on our website.  Please note that I manually edited the '_sip_v1.0.tab' file to report where the v1.0 bundle.xml file is located.  Likewise I had to edit the 'sip_v1.0.xml' file to correct the md5sum of the SIP table.  I did not edit the AIP files because I as not sure if I should.  Should these be edited?  If this works out will work on submitting v2, v3, v4, etc of the bundle.

Please note that I manually edited the '*_sip_v1.0.xml' file to correct an [issue](https://github.com/NASA-PDS/pds-deep-archive/issues/99) with a wrong <aip_label_checksum> value being reported.  I was using pds-deep-archive 0.4.0

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@tbarnes4 this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID below:

SIP LID:
* urn:nasa:pds:system_bundle:product_sip_deep_archive:compil-comet_v1.0_20210429
---
Regarding your two comments: 

> Please note that I manually edited the '*_sip_v1.0.xml' file to correct an issue with a wrong <aip_label_checksum> value being reported. I was using pds-deep-archive 0.4.0

We strongly encourage letting the PDS Deep Archive do as much of the work as possible. However, I also realize that although the issue you mentioned had been addressed, we had not yet released a stable version with the fix, and thus you were left to your own devices. Thank you for taking the initiative! We have since released a new version; please download and use this [latest version](https://github.com/NASA-PDS/pds-deep-archive/releases/tag/v1.0.0), and let us know if there are any issues.


> This is my first test of uploading a bundle that has been superseded on our website. Please note that I manually edited the '_sip_v1.0.tab' file to report where the v1.0 bundle.xml file is located. Likewise I had to edit the 'sip_v1.0.xml' file to correct the md5sum of the SIP table. I did not edit the AIP files because I as not sure if I should. Should these be edited? If this works out will work on submitting v2, v3, v4, etc of the bundle.

As mentioned above, we encourage a minimum of manual edits because instances like this can become tricky. However, maybe this won't be the case! Fingers crossed.

**Comment by tbarnes4** [comment]
@c-suh I will try the updated software once these are ingested at the NSSDCA (hopefully successfully).  In order to get all the superseded bundles uploaded, which Jordan said was preferred, this was the method I discussed with Jordan that we'd need to take.  One other idea just crossed my mind that I will try that might eliminate manual editing.  It will depend on how generous/forgiving your software is.  I too would prefer the pds-deep-archive to do all the work.  I'm always worried about manually editing things.  Once we get thru all our old superseded stuff, manually editing should be behind us.  Thanks!

**Comment by jordanpadams** [comment]
@tbarnes4 copy! the bug fix @c-suh mentions is regarding the aip_label_checksum. unfortunately, we do not yet have a solution for helping with the one-off directory changes and checksums updates. those unfortunately will have to be manual for the time being :-/

**Comment by c-suh** [comment]
Yes, sorry and thank you for clarifying, @jordanpadams. @tbarnes4, I'm glad we're on the same page about manual editing!

**Comment by tbarnes4** [comment]
> This set is in pre-ingest

@c-suh What does pre-ingest mean?

**Comment by c-suh** [comment]
@tbarnes4 the set for compil-comet has been archived
