### ISSUE TITLE
[ldd-release] <MESS> LDD Version:<1.1.0.1> IM Version:<1B00>

### ISSUE THREAD

**Issue by thareUSGS** [NASA-PDS/pdsen-operations#30]
* **Is the LDD IngestLDD in Github?** Yes
* **Has the LDD Namespace been registered in the [Namespace Registry](https://pds.nasa.gov/datastandards/schema/pds-namespace-registry.pdf)?** Yes
* **Need-by date**:  ASAP but not an emergency
* **Need-by date rationale**: To finalize a PDS3 migration

### Latest LDD is in Github
* **Build directory of Local Data Dictionary to release**: https://github.com/pds-data-dictionaries/ldd-mess/tree/master/build/release/1.B.0.0/1.1.0.1
* **PDS4 IM version to release with**: 1B00

This is a minor update for the existing mission dictionary and original IM 1B00.

**Comment by c-suh** [comment]
@thareUSGS, the LDD has been successfully validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#mess.

**Comment by thareUSGS** [comment]
@c-suh Don't hurt me. I had to do another manual build to replace the just posted build. The previous build you hosted for us 12 days ago is bad. It wasn't build with "lddtool -M" for a Mission dictionary which was still required for 1.B.0.0. Thus there just lines updated to URL to state "mission" in the top of the header. 

You can find the version fixed here (just generated 3 days ago -- and checked by Paul:
https://github.com/pds-data-dictionaries/ldd-mess/tree/master/build/release/1.B.0.0/1.1.0.1

**Comment by c-suh** [comment]
@thareUSGS I'm debating if I should let it slide or have my pound of flesh. The files from the zip file failed validation with `error.label.missing_file` because the .xml file references an .xsd and .sch file that are missing the LDD version from their filenames.

The validate report for your perusal: [report-PDS4_MESS_1B00_1101.txt](https://github.com/NASA-PDS/pdsen-operations/files/5655469/report-PDS4_MESS_1B00_1101.txt)

I'll let it slide :] Please let me know when this has been corrected and uploaded.

**Comment by thareUSGS** [comment]
ugh - looks like the older version of lddtool bit me. I do like the new lddtool (and github C.I.) which fixes this.

this should be fixed now...
https://github.com/pds-data-dictionaries/ldd-mess/tree/master/build/release/1.B.0.0/1.1.0.1

thanks

**Comment by c-suh** [comment]
Jordan will be very happy to know that you like our newer tools and interfaces!

@thareUSGS the fixed LDD has been successfully validated and posted to https://pds.nasa.gov/datastandards/dictionaries/index.shtml#mess.
