### ISSUE TITLE
NSSDCA Delivery: urn:nasa:pds:mro_accel

### ISSUE THREAD

**Issue by Astro-Joni** [NASA-PDS/pdsen-operations#77]
## Discipline Node Information

**Delivering Node**:ATM

**NSSDCA Delivery Package**: 
[mro_accel_bundle_v1.0_NSSDCA_20210310.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/6118516/mro_accel_bundle_v1.0_NSSDCA_20210310.tar.gz)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment]
@Astro-Joni, this set has been posted for NSSDCA processing. Beginning tomorrow, you can check the status  at https://nssdc.gsfc.nasa.gov/psi/ReportPDS4.jsp using the SIP LID(s) below:

SIP LID(s):
* urn:nasa:pds:system_bundle:product_sip_deep_archive:mro_accel_v1.0_20210310

**Comment by smclaughlin7** [comment]
@c-suh Could you please check the All Users read permissions for the five files posted in the manifest repository for this submission?

SIP: 
- urn:nasa:pds:system_bundle:product_sip_deep_archive:mro_accel_v1.0_20210310

Files:
- mro_accel_v1.0_20210310_aip_v1.0.xml
- mro_accel_v1.0_20210310_checksum_manifest_v1.0.tab
- mro_accel_v1.0_20210310_sip_v1.0.tab
- mro_accel_v1.0_20210310_sip_v1.0.xml
- mro_accel_v1.0_20210310_transfer_manifest_v1.0.tab

When I try to view any of these files online, I get "Forbidden. You don't have permission to access this resource" which to me means a file permission issue.  And I think it explains why our Puller did not retrieve this SIP when it ran the evening of 2021-03-12.

After tweaking the read permissions, please touch all five files to today's date so that the Puller gets 'em tonight.  Thanks!

**Comment by jordanpadams** [comment]
@c-suh this should just be a minor tweak to your script to `chmod 664 <file>` or in Python: https://docs.python.org/3/library/os.html#os.chmod

**Comment by c-suh** [comment]
@smclaughlin7, I've set the permissions and updated the dates. Fingers crossed!

**Comment by smclaughlin7** [comment]
@c-suh @jordanpadams @Astro-Joni Our front-end failed this submission because the URLs in the SIP manifest table are bad.  In particular, the bundle's root directory is repeated, e.g., https://pds-atmospheres.nmsu.edu/PDS/data/PDS4/mroa_bundle/mroa_bundle/bundle_mro_accel.xml.  ATM needs to rerun the Deep Archive software with the correct incantation to generate a totally new Deep Archive package then post this new package for PDS OPS to post/submit.

Hmm. GEO had the same problem. Perhaps this should be called out in the Deep Archive software instructions to the nodes?

**Comment by jordanpadams** [comment]
@smclaughlin7 it is `#4` of the https://nasa-pds.github.io/pds-deep-archive/usage/index.html#pds-delivery-checklist, but it appears we need to improve that.

**Comment by c-suh** [comment]
https://github.com/NASA-PDS/pdsen-operations/issues/85 has been closed
